#页面日期传入后台时，指定格式化
spring:
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss

  #数据库配置
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    user:
      name: admin  # spring security 安全认证的默认账号与密码
      password: 123456

#指定 myBatis 核心配置文件与 Mapper 映射 xml 文件
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

#自定义属性，是否开启 Swagger 在线文档功能，通常上线之后，可以关掉.
sys:
  config:
    swagger-is-open: true


